#!/usr/bin/env python3
"""Emit src/cp437_font.cpp from the vendored Modern DOS 8x16 bitmaps.

256 glyphs of 16 bytes is data, and this repo's rule is that anything which is
a list in its source arrives in `src/` mechanically - the Instructions, the
Credits and the cutscene all come in that way. A font is the same case with
4,096 more chances to make a typo nobody would ever spot.

Input is `third_party/moderndos-8x16/fontlist.js`, vendored unmodified. Each
line is one glyph: sixteen bytes, one scanline each, MSB leftmost, which is the
layout a VGA character generator holds and what `textscreen.cpp` indexes.

Usage:
    tools/gen_cp437_font.py > src/cp437_font.cpp
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "third_party", "moderndos-8x16", "fontlist.js")

ROW = re.compile(r"^\s*\[([0-9a-fx, ]+)\],")


def load(path):
    glyphs = []
    for line in open(path):
        m = ROW.match(line)
        if not m:
            continue
        vals = [int(v, 16) for v in m.group(1).split(",") if v.strip()]
        if len(vals) != 16:
            raise SystemExit(f"glyph {len(glyphs)} has {len(vals)} rows, expected 16")
        glyphs.append(vals)
    return glyphs


def main():
    glyphs = load(SRC)
    if len(glyphs) != 256:
        raise SystemExit(f"expected 256 glyphs, got {len(glyphs)}")

    out = sys.stdout.write
    out("// GENERATED by tools/gen_cp437_font.py - do not edit.\n")
    out("//\n")
    out("// Modern DOS 8x16, by Jayvee Enaguas, via susam/pcface. MIT or CC0;\n")
    out("// see third_party/moderndos-8x16/ for the licences, the provenance, and\n")
    out("// why this font rather than the better-known CC BY-SA one.\n")
    out("//\n")
    out("// 256 glyphs x 16 scanlines, one byte per scanline, MSB leftmost.\n")
    out("\n#include \"textscreen.h\"\n\nnamespace tubes {\n\n")
    out("const uint8_t kCp437Font8x16[256][16] = {\n")
    for i, g in enumerate(glyphs):
        body = ", ".join(f"0x{b:02x}" for b in g)
        ch = chr(i) if 32 <= i < 127 else " "
        note = f"  // {i:3d}  {ch!r}" if 32 <= i < 127 else f"  // {i:3d}"
        out(f"    {{{body}}},{note}\n")
    out("};\n\n}  // namespace tubes\n")


if __name__ == "__main__":
    main()
