#!/usr/bin/env python3
"""Emit src/ending.cpp from the disassembly of `1000:9499`.

The wave-75 ending is twelve strings and two screens, and every one of the
twelve is a fixed push sequence:

    PUSH x           PUSH 0            { OutTextCentred }
    PUSH y           PUSH 0x13f
    PUSH colour      PUSH y
    PUSH mode        PUSH colour
    MOV DI,<off>     PUSH mode
    PUSH CS          MOV DI,<off>
    PUSH DI          PUSH CS / PUSH DI
    CALLF 2000:36ab  CALLF 2000:37ea

so they can be read off rather than typed. Twelve is few enough that typing
them looks harmless, which is exactly why it is not: "prove the existance of
the new elements" is the game's own spelling and a silent correction of it
would be a transcription error nobody would ever catch.

`2000:3fab` picks the font, and which one is the resource slot it is handed:
`DS:0x2110` is STARTREK.816 (the heading) and `DS:0x2118` is TINY6X8.88 (the
small one), from the loads at `1000:b0f6` and `1000:b0b6`.

Usage, from the tooling checkout (see CLAUDE.md):
    gen_ending.py disasm-9499.txt ending-strings.txt > REPO/src/ending.cpp
"""
import re
import sys

WRITE_AT, WRITE_MID = "0x2000:36ab", "0x2000:37ea"
SET_FONT = "0x2000:3fab"
FONTS = {0x2110: "kHeading", 0x2118: "kSmall"}
INSN = re.compile(r"^1000:([0-9a-f]{4})\s+(.*?)\s*$")


def load_disasm(path):
    out = []
    for line in open(path):
        m = INSN.match(line.rstrip("\n"))
        if m:
            out.append((int(m.group(1), 16), m.group(2)))
    return out


def load_strings(path):
    data = {}
    row = re.compile(r"1000:([0-9a-f]{4})\s+((?:[0-9a-f]{2} )+)")
    for line in open(path):
        m = row.search(line)
        if not m:
            continue
        base = int(m.group(1), 16)
        for i, b in enumerate(m.group(2).split()):
            data[base + i] = int(b, 16)
    return data


def pascal(data, off):
    """Turbo Pascal short string: a length byte, then that many characters."""
    n = data[off]
    return "".join(chr(data[off + 1 + i]) for i in range(n))


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def signed(v):
    return v - 0x100 if v > 0x7F else v


def main():
    ins = load_disasm(sys.argv[1])
    strs = load_strings(sys.argv[2])

    pushes, font, items = [], "kSmall", []
    for _, text in ins:
        m = re.match(r"PUSH (-?0x[0-9a-f]+|\d+)$", text)
        if m:
            pushes.append(int(m.group(1), 16 if "x" in m.group(1) else 10))
            continue
        m = re.match(r"MOV DI,(0x[0-9a-f]+)$", text)
        if m:
            pushes.append(int(m.group(1), 16))
            continue
        # `PUSH word ptr [0x2110]` - a resource slot, which is what names the
        # font. Without this the two heading lines came out as small text.
        m = re.match(r"PUSH word ptr \[(0x[0-9a-f]+)\]$", text)
        if m:
            pushes.append(int(m.group(1), 16))
            continue
        if text in ("PUSH CS", "PUSH DI", "PUSH SS"):
            continue
        if text.startswith("CALLF " + SET_FONT):
            # Pushed (ptrHi, ptrLo, w, h, hspace, vspace); the LOW word of the
            # far pointer is the DGROUP slot, and that is what names the font.
            slot = pushes[-5] if len(pushes) >= 5 else 0
            font = FONTS.get(slot, font)
            pushes = []
            continue
        if text.startswith("CALLF " + WRITE_AT):
            x, y, colour, mode, off = pushes[-5:]
            items.append((font, x, y, signed(colour) & 0xFF, mode,
                          pascal(strs, off), False, x))
            pushes = []
            continue
        if text.startswith("CALLF " + WRITE_MID):
            # OutTextCentred(left, right, y, colour, mode, s) - centred over
            # the two bounds, which are 0 and 319 at every call here.
            left, right, y, colour, mode, off = pushes[-6:]
            items.append((font, left, y, signed(colour) & 0xFF, mode,
                          pascal(strs, off), True, right))
            pushes = []
            continue
        pushes = []

    print("// GENERATED by tools/gen_ending.py - do not edit.")
    print("//")
    print("// The wave-75 ending's text, read out of `1000:9499` rather than")
    print("// typed. See the tool's header for why twelve strings still get a")
    print("// generator.")
    print('#include "ending.h"')
    print()
    print("namespace tubes {")
    print()
    print("const EndingLine kEndingLines[kEndingLineCount] = {")
    for font, x, y, colour, mode, text, centred, right in items:
        print("    {EndingFont::%s, %d, %d, %d, %d, %d, %s, %s}," %
              (font, x, right, y, colour, mode,
               "true" if centred else "false", cstr(text)))
    print("};")
    print()
    print("}  // namespace tubes")


if __name__ == "__main__":
    main()
