// GENERATED by tools/gen_cutscene.py from the disassembly of
// `1b2e:1651`. Do not edit - regenerate.
//
// The story is the game's own text, extracted rather than transcribed
// for the same reason the Instructions are: a line of it mistyped
// would never be noticed.
#include "cutscene.h"

namespace tubes {
namespace {
const CutsceneItem kPage1[] = {
    {CutsceneItem::kBar, 0, 25, 320, 18, nullptr},   // w x h
    {CutsceneItem::kText, 7, 30, 154, 1, "In a lab far, far away in the Great White North..."},
};
const CutsceneItem kPage2[] = {
    {CutsceneItem::kBar, 0, 4, 320, 95, nullptr},   // w x h
    {CutsceneItem::kText, 7, 9, 154, 1, "Dr. Lanny B. Brilliant was completing his  work  on"},
    {CutsceneItem::kText, 7, 19, 154, 1, "the creation of eight new elements not yet included"},
    {CutsceneItem::kText, 7, 29, 154, 1, "on the periodic table of elements:"},
    {CutsceneItem::kAtom, 14, 40, 1, 0, nullptr},
    {CutsceneItem::kText, 34, 43, 154, 1, "Redium"},
    {CutsceneItem::kAtom, 88, 40, 2, 0, nullptr},
    {CutsceneItem::kText, 108, 43, 154, 1, "Greenium"},
    {CutsceneItem::kAtom, 168, 40, 3, 0, nullptr},
    {CutsceneItem::kText, 188, 43, 154, 1, "Bluium"},
    {CutsceneItem::kAtom, 238, 40, 4, 0, nullptr},
    {CutsceneItem::kText, 258, 43, 154, 1, "Cyanium"},
    {CutsceneItem::kAtom, 14, 60, 5, 0, nullptr},
    {CutsceneItem::kText, 34, 63, 154, 1, "Purplium"},
    {CutsceneItem::kAtom, 88, 60, 6, 0, nullptr},
    {CutsceneItem::kText, 108, 63, 154, 1, "Yellowium"},
    {CutsceneItem::kAtom, 168, 60, 7, 0, nullptr},
    {CutsceneItem::kText, 188, 63, 154, 1, "Pinkium"},
    {CutsceneItem::kAtom, 238, 60, 4, 0, nullptr},
    {CutsceneItem::kText, 258, 63, 154, 1, "Flashium"},
    {CutsceneItem::kText, 7, 76, 154, 1, "Already  going  over  his  Nobel  Prize  acceptance"},
    {CutsceneItem::kText, 7, 86, 154, 1, "speech in his head..."},
};
const CutsceneItem kPage3[] = {
    {CutsceneItem::kBar, 0, 25, 320, 18, nullptr},   // w x h
    {CutsceneItem::kText, 7, 30, 154, 1, "Suddenly, his future didn't seem so bright..."},
};
const CutsceneItem kPage4[] = {
    {CutsceneItem::kBar, 0, 4, 320, 50, nullptr},   // w x h
    {CutsceneItem::kText, 7, 10, 154, 1, "Lanny hadn't researched his new elements enough  to"},
    {CutsceneItem::kText, 7, 20, 154, 1, "have discovered they were highly  unstable.  Before"},
    {CutsceneItem::kText, 7, 30, 154, 1, "he could  react,  they  were  everywhere.   He  had"},
    {CutsceneItem::kText, 7, 40, 154, 1, "nothing for the Nobel Prize committee to assess."},
};
const CutsceneItem kPage5[] = {
    {CutsceneItem::kBar, 0, 4, 320, 64, nullptr},   // w x h
    {CutsceneItem::kText, 7, 10, 154, 1, "But there is still hope!  Lanny knows that  he  can"},
    {CutsceneItem::kText, 7, 20, 154, 1, "stabilize the atoms if he bonds three or more atoms"},
    {CutsceneItem::kText, 7, 30, 154, 1, "of the same element  together  forming  a  molecule"},
    {CutsceneItem::kText, 7, 40, 154, 1, "chain."},
    {CutsceneItem::kText, 7, 55, 154, 1, "Maybe you can help..."},
};
}  // namespace

const CutscenePage kCutscenePages[kCutscenePageCount] = {
    {kPage1, sizeof(kPage1) / sizeof(kPage1[0]), 2,
     {86, 122, 28, 41, 5, 0, nullptr},
     {0, 0, 0, 0, 0, 0, nullptr},
     nullptr},
    {kPage2, sizeof(kPage2) / sizeof(kPage2[0]), 18,
     {86, 122, 28, 41, 8, 0, nullptr},
     {238, 60, 16, 13, 7, 0, nullptr},
     nullptr},
    {kPage3, sizeof(kPage3) / sizeof(kPage3[0]), 4,
     {86, 122, 28, 41, 8, 0, nullptr},
     {258, 119, 60, 46, 4, -1, "BUBBLE.SFX"},
     "WHATTHE.SFX"},
    {kPage4, sizeof(kPage4) / sizeof(kPage4[0]), 12,
     {86, 122, 28, 66, 25, 25, "NOOOO.SFX"},
     {258, 119, 60, 46, 16, 0, nullptr},
     nullptr},
    {kPage5, sizeof(kPage5) / sizeof(kPage5[0]), 10,
     {0, 0, 0, 0, 0, 0, nullptr},
     {0, 0, 0, 0, 0, 0, nullptr},
     nullptr},
};

// The two frame lists, recovered from the loads and the pointer
// copies in `1b2e:1651` - 10 files across 26 slots and 16 across 17.
const char* const kWriteFrames[kWriteFrameCount] = {
    "WRITE1.GFX",
    "WRITE2.GFX",
    "WRITE2.GFX",
    "WRITE3.GFX",
    "WRITE3.GFX",
    "WRITE4.GFX",
    "WRITE4.GFX",
    "WRITE3.GFX",
    "WRITE3.GFX",
    "WRITE5.GFX",
    "WRITE6.GFX",
    "WRITE6.GFX",
    "WRITE6.GFX",
    "WRITE6.GFX",
    "WRITE6.GFX",
    "WRITE6.GFX",
    "WRITE6.GFX",
    "WRITE7.GFX",
    "WRITE7.GFX",
    "WRITE8.GFX",
    "WRITE8.GFX",
    "WRITE8.GFX",
    "WRITE8.GFX",
    "WRITE8.GFX",
    "WRITE9.GFX",
    "WRITE9.GFX",
};
const char* const kBlowFrames[kBlowFrameCount] = {
    "EXPLOD1.GFX",
    "EXPLOD2.GFX",
    "EXPLOD3.GFX",
    "EXPLOD4.GFX",
    "EXPLOD5.GFX",
    "EXPLOD6.GFX",
    "EXPLOD7.GFX",
    "EXPLOD8.GFX",
    "EXPLOD9.GFX",
    "EXPLOD10.GFX",
    "EXPLOD11.GFX",
    "EXPLOD12.GFX",
    "EXPLOD13.GFX",
    "EXPLOD14.GFX",
    "EXPLOD15.GFX",
    "EXPLOD16.GFX",
    "EXPLOD16.GFX",
};

// `2321:0ac0`, extracted the same way: nine fills in terms of the
// panel's own x, y, w, h.
const PanelFill kPanelFills[kPanelFillCount] = {
    {0, 0, 0, 0, 0, 0, 1, 1, 7},
    {0, 0, 0, 0, 0, 0, 1, 0, 15},
    {0, 0, 0, 0, 0, 0, 0, 1, 15},
    {-3, 2, 0, -4, 1, 0, 0, 1, 15},
    {3, -3, -5, 0, 0, 1, 1, 0, 15},
    {2, 2, -4, 0, 0, 0, 1, 0, 8},
    {-1, 1, 0, -1, 1, 0, 0, 1, 8},
    {2, 2, 0, -4, 0, 0, 0, 1, 8},
    {1, -1, -1, 0, 0, 1, 1, 0, 8},
};

}  // namespace tubes
