// GENERATED by tools/gen_ending.py - do not edit.
//
// The wave-75 ending's text, read out of `1000:9499` rather than
// typed. See the tool's header for why twelve strings still get a
// generator.
#include "ending.h"

namespace tubes {

const EndingLine kEndingLines[kEndingLineCount] = {
    {EndingFont::kHeading, 0, 319, 38, 159, 3, true, "Congratulations"},
    {EndingFont::kHeading, 0, 319, 41, 159, 3, true, "_____________"},
    {EndingFont::kSmall, 78, 78, 60, 155, 1, false, "You've done it!  Lanny  now"},
    {EndingFont::kSmall, 78, 78, 69, 155, 1, false, "has  enough  molecules   to"},
    {EndingFont::kSmall, 78, 78, 78, 155, 1, false, "prove the existance of  the"},
    {EndingFont::kSmall, 78, 78, 87, 155, 1, false, "new elements."},
    {EndingFont::kSmall, 78, 78, 100, 155, 1, false, "In appreciation,  Lanny has"},
    {EndingFont::kSmall, 78, 78, 109, 155, 1, false, "made you  his  partner  and"},
    {EndingFont::kSmall, 78, 78, 118, 155, 1, false, "even named an element after"},
    {EndingFont::kSmall, 78, 78, 127, 155, 1, false, "you."},
    {EndingFont::kSmall, 78, 78, 140, 166, 2, false, "His  discovery  has  earned"},
    {EndingFont::kSmall, 78, 78, 150, 166, 2, false, "you both the..."},
};

}  // namespace tubes
